# Generated by Django 3.2.20 on 2023-12-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_county',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
