# Generated by Django 5.0 on 2024-01-03 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='full_name',
            new_name='last_name',
        ),
    ]
