# Generated by Django 5.0 on 2024-01-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_full_name_purchase_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
