# Generated by Django 3.2.20 on 2023-12-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_catalogue_auto_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories_photo/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
