# Generated by Django 3.2.20 on 2023-12-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20231218_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='friendly_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='friendly_name',
        ),
        migrations.AddField(
            model_name='brand',
            name='display_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='display_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
