# Generated by Django 5.0 on 2023-12-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231219_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='auto_brand',
            field=models.CharField(blank=True, choices=[('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Mercedes', 'Mercedes'), ('Toyota', 'Toyota'), ('Mitsubishi', 'Mitsubishi'), ('Citroen', 'Citroen')], max_length=24, null=True),
        ),
    ]
