# Generated by Django 5.0 on 2024-01-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_catalogue_auto_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wish_lists',
        ),
    ]
